### ISSUE TITLE
Use Weak.Make or Ephemeron.K1?

### ISSUE THREAD

**Issue by edwintorok** [backtracking/ocaml-hashcons#11]
Looking at the implementation of hashcons.ml it seems to grow the weak set very slowly (by +3) every time.
That is the same bug that got fixed in OCaml long ago: https://github.com/ocaml/ocaml/commit/db2092907f2eddcaf0b72f4bd0f429001364dbe5

Why3 also seems to have switched to using Weak directly: https://gitlab.inria.fr/why3/why3/-/commit/059eda2a2758a857359d88828afd4bcf0e07e27a

There are other hash-consing libraries on opam (e.g. https://git.zapashcanon.fr/zapashcanon/hc/src/branch/master/src/hc.ml), but this one is more complete (it saves the hash key in a field for easy computation of other hashes, and has hash set and map implementations).

**Comment by edwintorok** [comment]
It is a bit tricky to implement the non-functorized version of the signature, but the following compiles (I haven't benchmarked it yet):  https://github.com/edwintorok/ocaml-hashcons/commits/weakephe/

Unfortunately Ephemeron.K1 doesn't have an `iter` function (and I couldn't use Weak.Make here because it wants a concrete type 't' for the key, not a polymorphic one), I'm not sure what the best way forward on that one would be, perhaps:
* use Weak.Make for the functorized implementation
* keep the current implementation for the non-functorized version but port bugfixes from the OCaml compiler to it?

What do you think?

**Comment by backtracking** [comment]
Hi @edwintorok !
Many thanks for reporting this. Indeed, it is much likely that I copied some code from `Weak.ml` a long time ago, prior to the 2008 bug fix you mention. I should at least backport the OCaml bug fix as you suggest.

**Comment by backtracking** [comment]
May be one of the reasons it wasn't noticed earlier is that, in many cases, hash-consing is more something we re-implement from scratch (as a pattern) instead of using a library.

**Comment by edwintorok** [comment]
> hash-consing is more something we re-implement from scratch (as a pattern) instead of using a library.

Indeed, although this library has a few extra nice tricks that I haven't seen elsewhere (other than the Why3 repo I linked), like storing the hash key (which then allows to efficiently hash-cons recursive data structures), or storing a unique tag from hash-consing that allows to build efficient sets :)

**Comment by backtracking** [comment]
A first fix would be to replace the two occurrences of `sz+3` by `3*sz/2+3`.
What do you think?

**Comment by edwintorok** [comment]
> A first fix would be to replace the two occurrences of `sz+3` by `3*sz/2+3`. What do you think?

Sounds good.

Looking at the ocaml code commit I think this may be another (small) optimization, it'd avoid creating a copy if the hash doesn't match:
```diff
-      if i >= sz then ifnotfound index
-      else begin
+      if i >= sz then ifnotfound h index
+      else if h = hashes.(i) then begin
               match get_copy bucket i with
```

And an earlier oneliner might be useful to port too:
https://github.com/ocaml/ocaml/commit/62fc7043b61cdaac208de799f257ca886d264e4d
I think without this `limit` would keep growing everytime you resize the weak array (from 3x,5x,7x,etc.), allowing more and more keys to collide the bigger the table gets.

**Comment by backtracking** [comment]
> ```diff
> -      if i >= sz then ifnotfound index
> -      else begin
> +      if i >= sz then ifnotfound h index
> +      else if h = hashes.(i) then begin
>                match get_copy bucket i with
> ```

We can't do that here, as the hash value is stored inside the `hash_consed` record, and not in a separate array as in the OCaml code. So we have to look in the weak array. Once we have done that, we directly check for equality. We could check for the hash value first, but I don't think this would be a significant improvement, as equality is typically O(1) when we do hash-consing.

**Comment by backtracking** [comment]
I removed the `limit <- limit+2`, following your suggestion.

On my own tests (I added two new tests in the repo), I don't see much performance improvement with these two backports. Please let me know if it makes a difference for you.

**Comment by backtracking** [comment]
And let me know if you want me to make a release 1.4 with these changes.

**Comment by edwintorok** [comment]
Thanks for the changes. To see the performance difference the weak table needs to grow, so try setting its initial size to `1` in `test_qs.ml`.

And then I see this (if I compare latest master vs reverting one of the commits , e.g. `46ce4e602a185fe7e6797e267fef788a9a84a0ca` ):

```diff
diff --git a/test_qs.ml b/test_qs.ml
index f62e8b1..4855f8a 100644
--- a/test_qs.ml
+++ b/test_qs.ml
@@ -33,7 +33,7 @@ module Term = Hashcons.Make(
       | Abs t -> (19 * t.hkey + 1)
       | App (u,v) -> (19 * (19 * u.hkey + v.hkey) + 2)
   end)
-let ht = Term.create 10007
+let ht = Term.create 1
```

I've copied the test_qs.exe from the revision with the revert to reverted.exe and then compared with master:
```
hyperfine _build/default/test_qs.exe ./reverted.exe
Benchmark 1: _build/default/test_qs.exe
  Time (mean ± σ):      1.666 s ±  0.019 s    [User: 1.659 s, System: 0.003 s]
  Range (min … max):    1.640 s …  1.703 s    10 runs
 
Benchmark 2: ./reverted.exe
  Time (mean ± σ):      4.829 s ±  0.024 s    [User: 4.814 s, System: 0.002 s]
  Range (min … max):    4.780 s …  4.871 s    10 runs
 
Summary
  _build/default/test_qs.exe ran
    2.90 ± 0.04 times faster than ./reverted.exe
```

The difference is significant :)

And here is the output with the table stats:
```
subst count: 1530
top heap words: 206310 (805 kb)
table length: 3591 / nb. entries: 6204 / sum of bucket length: 10777
smallest bucket: 0 / median bucket: 3 / biggest bucket: 13
```

reverted:
```
subst count: 1529
top heap words: 194558 (759 kb)
table length: 468 / nb. entries: 6204 / sum of bucket length: 8464
smallest bucket: 7 / median bucket: 22 / biggest bucket: 36
```

**Comment by edwintorok** [comment]
And here is a comparison of the same test_qs.ml (with hashtable of size 1 initially) using weak hashtables/ephemerons:
```
hyperfine _build/default/test_qs.exe ./weakephe.exe
Benchmark 1: _build/default/test_qs.exe
  Time (mean ± σ):      1.218 s ±  0.013 s    [User: 1.212 s, System: 0.002 s]
  Range (min … max):    1.209 s …  1.243 s    10 runs
 
Benchmark 2: ./weakephe.exe
  Time (mean ± σ):     790.0 ms ±   3.0 ms    [User: 784.7 ms, System: 3.0 ms]
  Range (min … max):   786.9 ms … 797.7 ms    10 runs
 
Summary
  ./weakephe.exe ran
    1.54 ± 0.02 times faster than _build/default/test_qs.exe
```

```
./weakephe.exe
subst count: 1531
top heap words: 226722 (885 kb)
table length: 1060 / nb. entries: 6204 / sum of bucket length: 8876
smallest bucket: 0 / median bucket: 7 / biggest bucket: 22
```

Their speeds are much closer together now, the difference seems to come from using `Weak.get_copy` vs `Weak.get`.

If I replace `Weak.get_copy` with `Weak.get` then they are nearly identical:
```
    1.06 ± 0.00 times faster than _build/default/test_qs.exel:
```

**Comment by edwintorok** [comment]
> And let me know if you want me to make a release 1.4 with these changes.

I think a new release would also solve https://github.com/backtracking/ocaml-hashcons/issues/6

(there are also 2 PRs -- not from me -- on this repo, do you want to review/include them in this release or the next?)

**Comment by backtracking** [comment]
It seems indeed that `get_copy` is unnecessarily cautious here. I changed to `get`. Thanks for pointing this out.

**Comment by backtracking** [comment]
I reviewed and merged the two PR. I'm now ready to make a release (and to close this issue) if everything is fine with you.

**Comment by edwintorok** [comment]
The code looks good, but there is something wrong with the CI, it fails nearly everywhere. 
This should hopefully fix most of the failures https://github.com/backtracking/ocaml-hashcons/pull/12

**Comment by backtracking** [comment]
https://github.com/ocaml/opam-repository/pull/25148

**Comment by edwintorok** [comment]
Thanks a lot for updating the library, I think we can close this issue now.
