### ISSUE TITLE
Why is the empty bucket shared in create and clear?

### ISSUE THREAD

**Issue by mrakgr** [backtracking/ocaml-hashcons#3]
```
let create sz =
  let sz = if sz < 7 then 7 else sz in
  let sz = if sz > Sys.max_array_length then Sys.max_array_length else sz in
  let emptybucket = Weak.create 0 in
  { table = Array.make sz emptybucket;
    totsize = 0;
    limit = 3; }

let clear t =
  let emptybucket = Weak.create 0 in
  for i = 0 to Array.length t.table - 1 do t.table.(i) <- emptybucket done;
  t.totsize <- 0;
  t.limit <- 3
```

I am doing a port of this library to F# and this is having me scratching my head. How is this possibly not an error?

**Comment by backtracking** [comment]
Buckets are implemented with arrays of weak pointers, of type Weak.t.
Buckets are indeed all initialized with the same 0-length array but this
is not an error.

You have to look at the code for function "add" where insertion is
performed: the internal function "loop" scans for an empty slot in the
bucket and none is found (which will be the case with a 0-length
bucket), then a larger bucket is allocated, values are copies from the
old one to the new one, and the new value is inserted.

So any attempt to insert into the 0-length, shared empty bucket will
result in the creation of a fresh bucket.

Note: If module Weak were implementing resizable arrays by itself, then
indeed it would be incorrect to share the same bucket.

--
Jean-Christophe

**Comment by mrakgr** [comment]
That is reassuring. Thank you for your prompt response. 

I've only started translating the code today for the sake a compiler project, so hopefully it should make more sense as I go along. Here is the repo for the [F# port](https://github.com/mrakgr/Hash-Consing).
